version: '3.1'

services:

  redmine:
    build:
      context: .
      dockerfile: Dockerfile-redmine
    container_name: CON1
    restart: always
    ports:
      - 80:3000
    environment:
      TZ: Asia/Tokyo
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
    volumes:
      - ./redmine/files:/usr/src/redmine/files
      - ./redmine/log:/usr/src/redmine/log
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/themes:/usr/src/redmine/public/themes

  db:
    image: mysql:5.7
    container_name: CON2
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    volumes:
      - ./db:/var/lib/mysql
